### ISSUE TITLE
Variable projectname?

### ISSUE THREAD

**Issue by StevenLangbroek** [MiniCodeMonkey/Vagrant-LAMP-Stack#10]
I'm pretty new to Vagrant, and was wondering if there's an easy way to implement a different projectname. From what I can gather now I have to change it everywhere in the Vagrantfile, isn't there like an option to set it as a variable at the start of the file?

Any pointers would be greatly appreciated!

**Comment by StevenLangbroek** [comment]
Should've investigated a bit more (Ruby isn't my forte). I've done it like so, is this how you would do it?

At top of file:

`PROJECT_NAME = 'projectname'`

Then further down:

`:db_dump        => "/var/www/#{PROJECT_NAME}/dump.sql",`

**Comment by MiniCodeMonkey** [comment]
Steven,

That's exactly how I would do it too.

You can check out how I implemented it in my other Vagrant Stack: https://github.com/MiniCodeMonkey/Vagrant-Laravel-Stack/blob/master/Vagrantfile
