### ISSUE TITLE
Error for "git clone" from the manual.

### ISSUE THREAD

**Issue by MaxProWeb** [MiniCodeMonkey/Vagrant-LAMP-Stack#16]
mini:lamp max$ git clone git@github.com:MiniCodeMonkey/Vagrant-LAMP-Stack.git
Cloning into 'Vagrant-LAMP-Stack'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by MiniCodeMonkey** [comment]
Try cloning via HTTPS instead

`git clone https://github.com/MiniCodeMonkey/Vagrant-LAMP-Stack.git`
