### ISSUE TITLE
vagrant up missing configuration. 

### ISSUE THREAD

**Issue by MaxProWeb** [MiniCodeMonkey/Vagrant-LAMP-Stack#17]
mini:Vagrant-LAMP-Stack max$ vagrant up
Bringing machine 'projectname' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
- Unknown configuration section 'berkshelf'.

**Comment by 0x73706f6f6b** [comment]
Did you try `$ gem install berkshelf` prior to doing a `$ vagrant up` ?
