### ISSUE TITLE
Auto Database Creation

### ISSUE THREAD

**Issue by whatnickcodes** [MiniCodeMonkey/Vagrant-LAMP-Stack#4]
**Feature Request:**

Be able to specify a database name and a path to an .sql dump so on Vagrant Up it automatically will build the database

**Comment by MiniCodeMonkey** [comment]
Flagged as enhancement

**Comment by babul** [comment]
This would be a very helpful enhancement! +1

**Comment by MiniCodeMonkey** [comment]
This is implemented now.

**Comment by whatnickcodes** [comment]
Greatness
